fix: workaround to make Airplay work on Safari
Stremio/stremio-video pull request #74
Opened 2024-04-20 22:54 UTC by IEduStu

Implemented the suggested workaround from [this comment](https://github.com/video-dev/hls.js/issues/5989#issuecomment-1825916766) to make Airplay work in Safari

2024-06-11 08:38 UTC, unclekingpin requested changes

2024-06-19 22:42 UTC, IEduStu commented on src/HTMLVideo/HTMLVideo.js
> +                                    videoElement.disableRemotePlayback = false;
No, this has to be done after calling `hls.attachMedia(videoElement);` and media is attaching, hence this is done on the `Hls.Events.MEDIA_ATTACHING` event.
I tested this with many other variations and this is the only way that got it working.

2024-06-19 22:43 UTC, IEduStu commented on src/HTMLVideo/HTMLVideo.js
> +                                    videoElement.appendChild(source);
Done

2024-07-22 16:49 UTC, AxelDeneu commented
Any update on this?

2024-07-26 15:34 UTC, IEduStu commented
It's ready to be merged for a long time on my end

2026-04-28 14:39 UTC, kKaskak commented
this is because the streaming server wont be able to be reached on the apple tv which will look for it on its own port needs some additional changes for this to be merged

2026-04-28 14:40 UTC, kKaskak commented
sorry for the half a year delay on this :D

2026-04-29 10:06 UTC, closed without merging